export const motivationalQuotes: string[] = [
    "The only way to do great work is to love what you do.",
    "Innovation distinguishes between a leader and a follower.",
    "Technology is best when it brings people together.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Stay hungry, stay foolish.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The best way to predict the future is to create it.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "The mind is everything. What you think you become.",
    "Strive not to be a success, but rather to be of value.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "If you want to lift yourself up, lift up someone else.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Do what you can, with what you have, where you are.",
    "It always seems impossible until it's done.",
    "Believe you can and you're halfway there.",
    "The journey of a thousand miles begins with a single step.",
    "The hard days are what make you stronger.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Work hard in silence, let your success be your noise.",
    "The only person you are destined to become is the person you decide to be.",
    "Happiness is not something readymade. It comes from your own actions.",
    "Dream bigger. Do bigger.",
    "Don't wait for opportunity. Create it.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Success doesn't just find you. You have to go out and get it.",
    "The only place where success comes before work is in the dictionary.",
    "Your limitation—it's only your imagination.",
    "Strength does not come from what you can do. It comes from overcoming the things you once thought you couldn't.",
    "The past cannot be changed. The future is yet in your power.",
    "You don't have to be great to start, but you have to start to be great.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "The best revenge is massive success.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "To live a creative life, we must lose our fear of being wrong.",
    "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you.",
    "It's hard to beat a person who never gives up.",
    "The expert in anything was once a beginner.",
    "Your attitude, not your aptitude, will determine your altitude.",
    "If not us, who? If not now, when?",
    "Light tomorrow with today!",
    "The only way to achieve the impossible is to believe it is possible.",
    "Try to be a rainbow in someone's cloud.",
    "Do not wait for a leader; do it alone, person to person.",
    "Nothing is impossible, the word itself says 'I'm possible'!",
    "The best way to appreciate your job is to imagine yourself without one.",
    "Change your thoughts and you change your world.",
    "The secret of getting ahead is getting started."
];
